postgres-adapter-project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 8.tcp.ngrok.io
      user: postgres
      password: mysecretpassword
      port: 16719
      dbname: postgres
      schema: my-schema
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
    prod:
      type: postgres
      host: 8.tcp.ngrok.io
      user: postgres
      password: mysecretpassword
      port: 16719
      dbname: postgres
      schema: my-prod-schema
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default